name: Build & Deploy

on:
  push:	
    branches:	
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Installing packages
        run: npm install

      - name: Build Gridsome site
        run: yarn build

      - name: Deploy to GitHub Pages
        run: yarn deploy
